### ISSUE TITLE
Error in rule filter_fastq

### ISSUE THREAD

**Issue by cliffbueno** [MathiasEskildsen/ONT-AmpSeq#8] opened 2024-11-09 08:21 UTC
Hello,

There seems to be an error at the fastq-fasta conversion, or fastq filtering step. Can you provide advice based on the error message below? I have 180 fastq samples and it seems to proceed through most of them but then quits. This happened to a different sample in a previous try. When I removed that one, then the error occurred on this one. Thanks!

Error in rule filter_fastq:
    jobid: 408
    input: tmp/samples/Q#_683_concat.fastq
    output: tmp/samples/Q#_683_filtered.fastq, tmp/read_count/Q#_683/Q#_683_total_reads_post_filtering.tsv
    log: logs/filter_fastq/Q#_683.log (check log file(s) for error message)
    conda-env: /data/cliffb/ONT_Compare/ONT_AmpSeq/ONT-AmpSeq-main/.snakemake/conda/c077327251f16e2049fb6bff0c5b389f_
    shell:
        
        chopper         --minlength 250         --maxlength 300         --headcrop 22         --tailcrop 22         -q 20         -t 2         < tmp/samples/Q#_683_concat.fastq         > tmp/samples/Q#_683_filtered.fastq

        # Count total reads
        num_reads=$(($(wc -l < "tmp/samples/Q#_683_filtered.fastq") / 4))
        # Put into a temporary file
        echo -e "Sample	Reads_Post_Filtering
Q#_683	$num_reads" > tmp/read_count/Q#_683/Q#_683_total_reads_post_filtering.tsv
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

**Comment by PSSchacksen** [comment] 2024-11-09 08:25
Hi Cliff

Could you please provide the respective log files for the error and the run? (log: logs/filter_fastq/Q#683.log)
Also, how are your files structured in the input dir.

Best regards
P

**Comment by cliffbueno** [comment] 2024-11-09 16:05
In logs/filter_fastq there are 136 of 180 file names there, but all of the log files are empty.
In ONT-AmpSeq-main/data/samples I have 180 .fastq.gz files.
In ONT-AmpSeq-main/tmp/read_counts there are 146 of 180 directories.
In ONT-AmpSeq-main/tmp/samples there are 145 files. 10 are _concat.fastq including the one that gave the error. 135 are _filtered.fasta.

**Comment by cliffbueno** [comment] 2024-11-09 16:37
Oh and this was the original script. Thanks for the help.
cd ~/ONT_Compare/ONT_AmpSeq/ONT-AmpSeq-main

mamba activate snakemake

screen snakemake --cores 24 --use-conda --config include_blast_output=False db_path_sintax=database/rdp_16s_v18.fa length_lower_limit=250 length_upper_limit=300 quality_cut_off=20 input_dir=data/samples metadata=data/metadata/Metadata180.txt

**Comment by PSSchacksen** [comment] 2024-11-10 14:49
Again it is very hard to assist in what goes wrong for your run without the log files. So please do provide one from a respective run, it may be named name.out instead of .log.

What might be happening is your thresholds are too narrow, resulting in empty files. 
Have you run the stats script on your samples and checked whether or not the samples giving you some trouble actually contain reads within your given filtering criteria? Using the stats script on all your samples provides a opportunity to check the content of your samples. If some of your samples does not contain reads within the given filtering criteria, it will result in a empty file potentially being deleted by snakemake and therefore causing an error. 

Do let me know how it looks like after having run stats on the samples giving you some trouble and providing the log (.out) file for a troublesome file.

If it is because a file does not contain sequences within your given filtering criteria, it will cause an error as snakemake cannot run with empty files. Meaning that you should remove the samples without anything in them from your starting folder and rerun the script.

**Comment by cliffbueno** [comment] 2024-11-10 19:10
Hi Patrick,

I wish I could provide a log file, but they're all empty! If I go to ONT-AmpSeq-main/logs there is capture_config.log which is empty, and three directories, convert_to_fasta, concatenate_fastq, filter_fastq. If I go into each of those directories, there are 137, 157, and 142 .log files, respectively, but they are all empty. In ONT-AmpSeq-main I also checked find ./ -type f -name "*.out" and it didn't find anything. 

It's good to know that having samples with no filtered reads will cause an error. But that doesn't seem to be the case here. I ran the stats script. So when I run the main pipeline on all samples the "Error in rule filter_fastq:" occurs on sample Q#_3794. So I looked at the read length vs. quality plot for that sample. Also attaching here. There are reads that are between 250-300 bp long and above Q20 which are the two thresholds I set. 
![LengthvsQualityScatterPlot_dot](https://github.com/user-attachments/assets/f44eee67-1d3b-4f16-ab4b-c7fbafc64681)

**Comment by PSSchacksen** [comment] 2024-11-10 20:19
Is there one in "path/logs/filter_fastq/" called "filter_fastq-sample=Q#_3794-numbers.out" or something similar?

There should also be a *_dot.html, could you try and open that for a failed file, then zoom into the 250-300 bp Read lengths range and check if there are reads? Just to ensure the length match when zoomed in.

Also could you do a "ls tmp/samples/" and check if the names look correct compared to your input files?

If these look good another thing you can try and do is: 
conda activate snakemake
snakemake --unlock

this sould force a rerun the failed samples if they look good

**Comment by cliffbueno** [comment] 2024-11-10 23:22
There are no .out files anywhere in ONT-AmpSeq-main/logs. I checked the .html file and can confirm that there are indeed reads 250-300 bp long and > Q20 for that sample.

There are 157 files in tmp/samples. 17 have sampleID_concat.fastq and 140 have sampleID_filtered.fasta. The sampleIDs are correct for all.

Okay, how do I use the snakemake --unlock command. Do I add --unlock as an argument in the main pipeline run, or once the run fails then do I make a separate snakemake --unlock call?

**Comment by PSSchacksen** [comment] 2024-11-11 10:12
Could you provide a list in txt format of all input filenames and in another file a list of all the filenames in the path/tmp/samples/ ?

Simply in your console write the following two lines:
conda activate snakemake
snakemake --unlock

Then delete the tmp and log dirs and rerun your samples again.

**Comment by cliffbueno** [comment] 2024-11-11 16:55
Here are the text files for the run prior to snakemake --unlock. Then after snakemake unlock, I got the same error in rule filter_fastq on sample Q#_3794.
[input_sample_names.txt](https://github.com/user-attachments/files/17706142/input_sample_names.txt)
[tmp_sample_names.txt](https://github.com/user-attachments/files/17706143/tmp_sample_names.txt)

**Comment by PSSchacksen** [comment] 2024-11-12 15:02
After going through the code for log files we have figured out why they are empty when using the desktop version that you are using and are looking into it.
I have also gone through the input and output names and cant seem to find a consistent reason for the unavailable files.

Could you provide a screenshot of the stats for C1R2 and C2R1, while zooming into the x-axis for the 250-300bp range using the html file?

If there is no issue within these could you perhaps try to use the local install of the ONT-AmpSeq, thereby the log files should provide more information and allow for more settings to be adjusted.

**Comment by cliffbueno** [comment] 2024-11-12 17:30
Interesting. Thanks for checking that.

Okay here are the stats for those.
![C1R2](https://github.com/user-attachments/assets/c554b196-c75b-4c12-8221-ae7efc767f9c)
![C2R1](https://github.com/user-attachments/assets/5659cea1-9981-40c4-b07b-3c61a0075ec8)

I don't quite follow the Desktop vs. Local install difference. I was basically following the Example Usage section of the Read Me.

**Comment by PSSchacksen** [comment] 2024-11-13 13:39
Could you by any chance rename all your files to exclude "_" in the names?

You are using the "screen snakemake" ONT-AmpSeq approach, instead of downloading the repository and running the "snakemake --profile path/profiles/config.yml" approach. Using this local installation of the workflow should provide the log files and more info (currently missing from the desktop version). See https://github.com/MathiasEskildsen/ONT-AmpSeq?tab=readme-ov-file#usage-of-workflow-local-repository-installation-aau-biocloud-hpc-users.

**Comment by cliffbueno** [comment] 2024-11-15 01:21
Ok I renamed everything without "_" but the same error occurred.

Then after editing profiles/biocloud/config.yaml and config/config.yaml for my computer and parameters, I tried `snakemake --profile /profiles/biocloud`. There were multiple errors including:
Error in rule merge_read_count
Error in rule capture_config
Error in rule relabel_merge
Log files were empty except for logs/capture_config/capture_config--16.out and capture_config--19.out

**Comment by PSSchacksen** [comment] 2024-11-15 11:47
At this point I'm sadly running out of ways i can try to figure out what happens without the log files.

Is it possible to try and use this stats script on your files. It merges the .gz files into a single file. Then could you possible try and use the provided path/fastq/*.fastq files as input? (i renamed the .sh extension to a .txt to be able to attach it)
[nanoplot.txt](https://github.com/user-attachments/files/17774915/nanoplot.txt)

If that does not work, then could you do a subset of your samples e.g. 10-20 samples of which you know the pipeline can handle and try to run that?

I hope this works then.

If neither works, then potentially there need to check the integrity of some of the merged fastq files using software like: https://github.com/stevekm/fastq-checker

**Comment by cliffbueno** [comment] 2024-11-15 17:35
Hi Patrick,

Yes, I agree, lack of log files makes it difficult to troubleshoot. I appreciate all of your ideas! Any progress on this front? "After going through the code for log files we have figured out why they are empty when using the desktop version that you are using and are looking into it."

I'll try out the new nanoplot code as well as subsetting and report back.

**Comment by MathiasEskildsen** [comment] 2024-11-21 12:23
Hi cliffbueno, 

Interesting that you are encountering errors in that many rules. 

Would it be possible for you to share your ".fastq" files, that prompts the errors? I would like to reproduce the errors myself and see what is going on, in order to improve the pipeline and resolve this issue.

We will be adding better logging to the pipeline in the next release version (Probably in mid/late-december, we are quite busy atm). We are primarily using slurm, which captures errors in a ".out" file. in the log-directory nicely. I have only tested ONT-AmpSeq on a non-slurm system, after the pipeline was finished - so I have not dug-through the log-files as it ran without errors at this point. 

I apologize for the inconvenience this has caused you and hopefully your experience can help us improve the pipeline :-)  

Best regards,
Mathias

**Comment by cliffbueno** [comment] 2024-11-27 23:22
Okay - with the updated sample IDs (no # or _) the output table is now correct. However, the number of OTUs is very inflated  and there are tons of OTUs with only 1 or 2 reads. For example, using the 99% clusters, I got 136378 OTUs and 116999 have only 1 or 2 reads total across 180 samples. I ran this exact same dataset through DADA2 and got 6020 ASVs. The same thing happened with the Zymo community standard (8 species). So there should be only 8 OTUs detected. We sequenced the Zymo on our MinION and I processed the data with both DADA2 and ONT-AmpSeq. DADA2 yielded 11 ASVs while ONT-AmpSeq yielded 2374 97% OTUs and 6834 99% OTUs. I wonder if ONT-AmpSeq is better suited for longer reads. Anyways, I no longer have the "Error in rule filter_fastq" error so closing this but thought you all might be interested to know about the OTU inflation in 253 bp V4 16S amplicons. Thank you again for your help.

**Closed** 2024-11-27 23:23 UTC

**Comment by PSSchacksen** [comment] 2024-11-28 13:40
Hi Cliff,

It’s great to hear that everything finally worked! Thank you for your input regarding the missing log files and for encouraging us to update the stats script—it’s much appreciated.

Regarding your samples, we’ve identified the root of the issue. You are using Illumina data, which employs a sequencing-by-synthesis paired-end platform, while ONT directly sequences molecules without the need for paired-end merging of reads. This fundamental difference between the two sequencing platforms also necessitates different processing workflows.

As clearly stated on the GitHub repository and in the ONT-AmpSeq paper, the tool is specifically designed for ONT data. It cannot directly process Illumina data without prior user preprocessing, such as merging paired-end reads. This difference also explains the high number of OTUs observed in your analysis.

Additionally, when using the 16S V4 region, it’s recommended to use 100% sequence identity (as employed by DADA2 for ASV generation - see doi.org/10.1093/bioinformatics/bty113), whereas ONT-AmpSeq generates OTUs. Moreover, you used cutadapt to remove primers—a feature already built into ONT-AmpSeq, as stated in the paper. By doing so, you inadvertently trimmed parts of your true sequences, which introduced additional genetic variation and inflated the OTU count.

Another important factor to consider is the quality gap between Illumina and ONT sequences. When annotating using ONT-AmpSeq, we employ a SINTAX-based approach, where the supported taxonomic rank provides taxonomy to a specified level (97% or 99% by default). This can result in a higher number of OTUs compared to Illumina data processed with DADA2 and ASVs. However, when visualizing the data, you may find stronger support for accurate taxonomic annotation using ONT-AmpSeq, due to the SINTAX algorithm, with many different OTUs being mapped to the same species, mitigating some of the effects of a higher number of OTUs during downstream analyses.

I hope this clarifies the challenges you encountered and provides a better understanding of how the platforms and pipelines differ.

Best regards,
Patrick

**Comment by cliffbueno** [comment] 2024-11-28 18:15
Hi Patrick,

Actually both of the datasets I ran ONT-AmpSeq on (Zymo, and the 180 environmental samples) were in fact ONT datasets from our MinION machine. But the interesting thing in this case is that we used our old Illumina adapters and constructs for the PCR.

Thanks for pointing out the cutadapt issue. I actually do not see that anywhere in the paper. Running a search for "cutadapt" finds only one mention of it in the main text and it's about demultiplexing. I suggest you all add mention of cutadapt, and more information about how primers are dealt with, in your "Description" paragraph in the README. 

You are right that if you collapse the OTUs to other taxonomic levels then the patterns look better.
